### PR TITLE
Remove references to global `qe_state`

### PR DESCRIPTION
**Pull request by chqrlie**
Massive API cleanup to remove global state references
Some crash bug fixes

### CODE REVIEW

**Comment by posguy99** [comment]
As of [e3c5bfd](https://github.com/qemacs/qemacs/commit/e3c5bfd457614773508feefdc12dbc60073030ed), qemacs is now emitting:

`qe: global-linum-mode enabled`

to the terminal window and leaving it in the terminal window when exiting.

I do have `global_linum_mode(1);` in my config, but I also have `set_indent_tabs_mode(0);` and that isn't being output to the terminal.

**Comment by chqrlie** [comment]
> As of [e3c5bfd](https://github.com/qemacs/qemacs/commit/e3c5bfd457614773508feefdc12dbc60073030ed), qemacs is now emitting:
> 
> `qe: global-linum-mode enabled`
> 
> to the terminal window and leaving it in the terminal window when exiting.
> 
> I do have `global_linum_mode(1);` in my config, but I also have `set_indent_tabs_mode(0);` and that isn't being output to the terminal, so it's not just a function invocation being output.

Thank you for this report.  Status messages emitted when parsing the configuration file should be ignored unless they are errors.  I shall investigate and fix this issue.

**Comment by chqrlie** [comment]
> Thank you for this report. Status messages emitted when parsing the configuration file should be ignored unless they are errors. I shall investigate and fix this issue.

@posguy99: I fixed this issue in the latest PR #47.
status messages produced at configuration time are just saved to the `*messages*` buffer while errors show in a popup window (as they already did).

**Comment by posguy99** [comment]
Yup, it's back to not sending messages to the terminal window. :)

**Pull request merged**
